"""add distributor stock and allocations

Revision ID: 4f63b6b0487e
Revises: 7cccd0c031fd
Create Date: 2026-06-09 22:26:16.605425
"""
from alembic import op
import sqlalchemy as sa


revision = '4f63b6b0487e'
down_revision = '7cccd0c031fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributor_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributor_stocks_distributor_id'), 'distributor_stocks', ['distributor_id'], unique=False)
    op.create_table('stock_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('salesperson_id', sa.Integer(), nullable=False),
    sa.Column('finance_user_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finance_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['salesperson_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['distributor_stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_allocations_finance_user_id'), 'stock_allocations', ['finance_user_id'], unique=False)
    op.create_index(op.f('ix_stock_allocations_salesperson_id'), 'stock_allocations', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_stock_allocations_stock_id'), 'stock_allocations', ['stock_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_stock_allocations_stock_id'), table_name='stock_allocations')
    op.drop_index(op.f('ix_stock_allocations_salesperson_id'), table_name='stock_allocations')
    op.drop_index(op.f('ix_stock_allocations_finance_user_id'), table_name='stock_allocations')
    op.drop_table('stock_allocations')
    op.drop_index(op.f('ix_distributor_stocks_distributor_id'), table_name='distributor_stocks')
    op.drop_table('distributor_stocks')
    # ### end Alembic commands ###
