"""add notifications table

Revision ID: 7cccd0c031fd
Revises: 0009_add_schedule_demand_handled
Create Date: 2026-06-09 21:49:45.735032
"""
from alembic import op
import sqlalchemy as sa


revision = '7cccd0c031fd'
down_revision = '0009_add_schedule_demand_handled'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
